#!/bin/bash

echo "[postBuild] Installing gfortran..."
apt-get update && apt-get install -y gfortran

echo "[postBuild] Compiling RDAAM_He..."
gfortran -O2 -o tc1d/bin/RDAAM_He tc1d/bin/RDAAM_He.f90

echo "[postBuild] Compiling ketch_aft..."
gfortran -O2 -o tc1d/bin/ketch_aft tc1d/bin/ketch_aft.f90

echo "[postBuild] Done."