#!/bin/bash

echo "[postBuild] Installing gfortran and make..."
apt-get update && apt-get install -y gfortran make gcc-12 g++-12

echo "[postBuild] Compiling ketch_aft and RDAAM_He using make..."
cd ketch_aft
make && make install
cd ../RDAAM_He
make && make install
cd ..

echo "[postBuild] Setting executable permissions..."
chmod +x bin/RDAAM_He
chmod +x bin/ketch_aft

echo "[postBuild] Done compiling executables."